server:
  port: 9999
spring:
  application:
    name: tens-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Swanyf/tens-times-dev.git
  rabbitmq:
    host: 192.168.110.132
management:   # 暴露触发消息总线的地址
  endpoints:
    web:
     exposure:
       include: bus-refresh   # 启用刷新配置
