server: 
  port: 9004

spring: 
  application:  
    name: tens-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.110.132:3306/tensquare_article?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: rootswan
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.110.132

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:7000/eureka   # 指定注册中心
    instance:
      prefer‐ip‐address: true   # 模块之间可以跨域访问