server: 
  port: 9002
spring: 
  application:  
    name: tens-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.110.132:3306/tensquare_recruit?characterEncoding=UTF8
    username: root
    password: rootswan
  jpa: 
    database: MySQL
    show-sql: true
